name: Get Label on PR

on: 
    pull_request:
        types: [opened, synchronize, reopened, labeled, unlabeled]


jobs:
  Label:
    runs-on: ubuntu-latest
    steps:
      - name: PR commit message
        run : |
          echo "PR commit message: ${{ github.event.pull_request.title }}"
          echo "PR commit message: ${{ github.event.pull_request.body }}"
          echo "PR commit message: ${{ github.event.pull_request.head }}"
          echo "PR commit message: ${{ github.event.pull_request.head.sha }}"
          echo "PR commit message: ${{ github.event.pull_request.merge_commit_sha }}"

      - id: bump
        uses: zwaldowski/match-label-action@v4
        with:
          allowed: major,minor,patch, none
          default_match: none
      - uses: zwaldowski/semver-release-action@v3
        id: release
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the created latest release time
        run: echo "The time was ${{ steps.release.outputs.version }}."

      # - name: "increment"
      #   shell: bassh
      #   id: increment_version
      #   run: |
      #       current_version=$(gh release list --limit 1 | grep Latest | awk '{ print $1;}')
      #       IFS='.' read -r major minor patch <<< "${current_version#v}"
      #       incremented_major=$((major + 1))
      #       incremented_minor=$((minor + 1))
      #       incremented_patch=$((patch + 1))
      #       echo "${incremented_major}.${incremented_minor}.${incremented_patch}"
      #       echo "${incremented_major}"
      #       echo "${incremented_minor}"
      #       echo "${incremented_patch}"
      #       major_version="v${incremented_major}.${minor}.${patch}"
      #       minor_version="v${major}.${incremented_minor}.${patch}"
      #       patch_version="v${major}.${minor}.${incremented_patch}"
      #       # echo "major_version=${major_version}" >> $GITHUB_OUTPUT
      #       # echo "minor_version=${minor_version}" >> $GITHUB_OUTPUT
      #       # echo "patch_version=${patch_version}" >> $GITHUB_OUTPUT
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      # - name: Use Incremented Versions
      #   run: |
      #       echo "Incremented Major Version: ${{ steps.increment_version.outputs.incremented_major_version }}"
      #       echo "Incremented Minor Version: ${{ steps.increment_version.outputs.incremented_minor_version }}"
      #       echo "Incremented Patch Version: ${{ steps.increment_version.outputs.incremented_patch_version }}"
  
  
    #   - name : Get tag 
    #     run: |
    #      echo $RELEASE_VERSION
    #      echo ${{ steps.vars.outputs.tag }}
    #   - uses: actions/checkout@v3
    #     with:
    #       fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
    #   - name: 'Get Previous tag'
    #     id: previoustag
    #     uses: "WyriHaximus/github-action-get-previous-tag@v1"
    #   - name: 'Get next minor version'
    #     id: semvers
    #     uses: "WyriHaximus/github-action-next-semvers@v1"
    #     with:
    #       version: ${{ steps.previoustag.outputs.tag }}
  
    #   - name: 'Get Label'
    #     run: |
    #       echo "Label: ${{ steps.semvers.outputs.patch }}"

    #   - name: 'Create new milestone'
    #     id: createmilestone
    #     uses: "WyriHaximus/github-action-create-milestone@v1"
    #     with:
    #       title: ${{ steps.semvers.outputs.patch }}
    #     env:
    #       GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    #