name: Test and Build
run-name: ${{ github.actor }} is testing out github actions
permissions:
  contents: write
  pages: write
  id-token: write
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Compile to Javascript
        run: npm run build
      - name: Run tests
        run: npm run testScript
      - name: Build Action
        run: npm run build
      - name: Check for code changes
        run: | 
          git fetch
          if [[ -n $(git status --porcelain) ]]; then
            echo "No code changes detected. Skipping commit and push."
            exit 0
          else
            echo "Code changes detected. Proceeding with commit and push."
            git add dist
            git config --global user.name ${{ github.actor }}
            git commit -m "Automated Build"
            git push
          fi


      # - name: Commit and push build to repo
      #   run: |
          
      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # - name: 'Run Azure CLI commands'
      #   run: az account show
      # - name: 'Run Azure Compliance Controls'
      #   uses: ./
      #   with:
      #     subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # - name: run command
      #   run: 'echo ${{ inputs.value }}'