name: Test and Build
run-name: ${{ github.actor }} is testing out github actions
permissions:
  contents: write
  pages: write
  id-token: write
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Compile to Javascript
        run: npm run build
      - name: Run tests
        run: npm run testScript
      # - name: Build Action
      #   run: npm run build
      # - name: Check for code changes in dist folder
      #   run: | 
      #     git fetch --quiet
      #     if [[ -n $(git status --porcelain dist) ]]; then
      #       echo "Code changes detected. Proceeding with commit and push."
      #       git add dist
      #       git config --global user.name ${{ github.actor }}
      #       git commit -m "Automated Build"
      #       git push
      #     else
      #       echo "No code changes detected for dist folder. Skipping commit and push."
      #     fi
          
      # - uses: JasonEtco/build-and-tag-action@v2
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}

        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      # - name: 'Run Azure Compliance Controls locally in repo'
      #   uses: ./
      #   with:
      #     subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure Compliance Controls'
        uses: Omegapoint/CydigAzureComplianceAction@v1
        with:
          subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


          # # # - name: run command
      # # #   run: 'echo ${{ inputs.value }}'
