name: test action
run-name: ${{ github.actor }} is running tests
permissions:
  contents: read
  pages: read
  id-token: write

on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build Action
        run: npm run build  
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Azure Compliance Controls'
        uses: ./
        with:
          subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          
      # - name: 'Run Azure Compliance Controls'
      #   uses: Omegapoint/CydigAzureComplianceAction@v1
      #   with:
      #     subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

